project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - index.qmd
    - project.qmd
    - hooks.qmd
    - discovery.qmd
    - continue-on-error.qmd
    - ci.qmd

website:
  title: "workr 1.1.0 demo"
  favicon: ""
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: RunProject
      - href: hooks.qmd
        text: Hooks
      - href: discovery.qmd
        text: Discovery
      - href: continue-on-error.qmd
        text: Continue-on-error
      - href: ci.qmd
        text: CI artifacts
    right:
      - icon: github
        href: https://github.com/zdz2101/workr_demoapp
        text: Repo

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  echo: true
  warning: false
  message: false
  freeze: false
